export const TOUR_IDS: Record<string, string> = {
  '/overview':                           'tour-step-inicio',
  '/dashboard':                          'tour-step-dashboard',
  '/results/:id':                        'tour-step-results',
  '/experiment/:id':                     'tour-step-generaciones',
  '/experiment/:id/best-per-generation': 'tour-step-mejor',
  '/experiment/:id/charts':              'tour-step-graficas',
  '/simulation/:id':                     'tour-step-simulacion',
  '/grafics':                            'tour-step-grafics',
  '/efficiency-calculator':              'tour-step-efficiency',
  '/users/add':                          'tour-step-users-add',
  '/users/manage':                       'tour-step-users-manage',
  '/fermentation':                       'tour-step-fermentation',
  '/fermentation-reports':               'tour-step-reports',
  '/announcements':                      'tour-step-announcements',
  '/messages':                           'tour-step-messages',
  '/chat':                               'tour-step-chat',
  '/groups':                             'tour-step-groups',
  '/admin/groups':                       'tour-step-admin-groups',
}
